### ISSUE TITLE
Need readme for the sample

### ISSUE THREAD

**Issue by jcookems** [azure-contrib/socket.io-servicebus#3]
I see there is an example, but no description about what it is or how to use it. When I do the simplest thing, `node app.js`, it yells at me:

```
The "sys" module is now called "util". It should have a similar interface.
   info  - socket.io started
...
Error: Must specify one of connectionString or serviceBusService in options
...
```

What options? In the environment? Passed as comman-line parameters? How to format? Etc.

**Comment by jkint** [comment]
More context would be helpful.  Can you post a transcript and maybe some of the code of your app?

**Comment by christav** [comment]
I am assuming that the "app.js" referred to is the one in the example/chat directory.

The complaint about sys is from socket.io - no way to fix that until socket.io fixes it, but it's just (one of many) info printouts, not fatal.

As for the readme for the example, I'll see what i can put together. For now, the usage is:

`node app.js <topic> <subscription> <port> <connection string>`
- topic is the topic name to use over service bus - if not specified, it looks for an environment variable SB_CHAT_TOPIC. If the environment variable's not set, it defaults to "sbchat"
- subscription is the name of the service bus subscription to use. If not specified, it looks for the environment variable SB_CHAT_SUBSCRIPTION, and if that's not set it defaults to 'client1'. You must ensure that each instance of the server is using a different subscription, otherwise messages will get lost.
- port is the TCP port to open for socket.io connections. If not given, uses environment variable SB_PORT, default is 3000
- connection string is the service bus connection string from the portal. Stick this in the environment variable SB_CONN rather than copy & pasting it on the command line. No default.

Yeah, I just wrote the readme, didn't I?

**Comment by glennblock** [comment]
The app uses the env variable PORT not SB_PORT as it should.

**Comment by glennblock** [comment]
@jcookems @christav is correct, this is socket.io, not anything we are doing.

**Comment by christav** [comment]
Ok, yeah, you changed it. I think "PORT" is ridiculously generic; the env variables should be namespaced to the app somehow some way.

**Comment by glennblock** [comment]
Hmm, I think you are misunderstanding. The PORT variable is a universal
variable that cloud hosters / hosting environments set. How would Azure
know to pass an SB_PORT variable? The user can't set it either as it's a
 dynamic port assigned in the cloud. In the case of iisnode it's a named
pipe.

**Comment by christav** [comment]
@glennblock you volunteered to write this.

**Comment by glennblock** [comment]
Yes i did. OK.

**Comment by jcookems** [comment]
looks good
